= PP-Module for Bluetooth Devices 



[cols="1,1,1,1,1,1,1,1"]
|===
| https://github.com/commoncriteria/bluetooth/tree/master[master] 
a| https://commoncriteria.github.io/bluetooth/master/bluetooth-release.html[📄]
a|[link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/master/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/master/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/master/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/master/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/master/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/master/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/master/pdf_count.svg[PDF Count]
| https://github.com/commoncriteria/bluetooth/tree/v1.0[v1.0] 
a| https://commoncriteria.github.io/bluetooth/v1.0/bluetooth-release.html[📄]
a|[link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/v1.0/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/v1.0/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/v1.0/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/v1.0/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/v1.0/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/v1.0/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/v1.0/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/v1.0/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/v1.0/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/v1.0/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/v1.0/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/bluetooth/blob/gh-pages/v1.0/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/bluetooth/gh-pages/v1.0/pdf_count.svg[PDF Count]
|===


https://github.com/commoncriteria/bluetooth/issues[image:https://img.shields.io/github/issues/commoncriteria/bluetooth.svg?maxAge=2592000[GitHub
issues Open]]

This repository hosts the draft version of the Protection Profile for
Bluetooth based on the
https://commoncriteria.github.io/pp/bluetooth/bluetooth-esr.html[Essential
Security Requirements (ESR)] for this technology class of products. This
repository is used to facilitate collaboration and development on the
draft document. See the link:#Release-Version[release] section if you
are looking for the officially released version for evaluations.

=== Draft Version (Up-to-date Master branch)

* https://commoncriteria.github.io/bluetooth/master/bluetooth-release.html[Protection
Profile Module for Bluetooth] (html)
* https://commoncriteria.github.io/bluetooth/master/bluetooth-sd.html[Protection
Profile Module Supporting Documents for Bluetooth] (html)

=== Release Version

* https://www.niap-ccevs.org/Profile/Info.cfm?PPID=425&id=425[Protection
Profile Module for Bluetooth]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/bluetooth/issues[repository issue
tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/bluetooth
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.
You shouldn’t need to modify it.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
